#pragma once

#define WINDOW_X 1200
#define WINDOW_Y 800
#define WINDOW_FREQUENCY 30
#define WINDOW_RELATION (float(WINDOW_X)/float(WINDOW_Y))

#define MAP_X 200
#define MAP_Y 200
#define MAP_SCALE 1
#define MAP_DETAIL_CHANGES 2
#define MAP_NUM_OCTAVES 8

#define CELL_COUNT_GENES 4
#define CELL_CHANCE_MUTATION 0.2f
#define CELL_STARTED_ENERGY 40
#define CELL_STARTED_NUM_GENE 0

#define SIMULATION_STARTED_CELLS 1200
#define SIMULATION_STARTED_SEA_LEVEL 0.15
#define SIMULATION_SEA_AMPLITUDE 0.1
#define SIMULATION_SEA_FREQUENCY 0.01
#define SIMULATION_COUNT_MEAT 30
#define SIMULATION_COUNT_MINERAL 10
