#pragma once

#define WINDOW_X 800
#define WINDOW_Y 800
#define WINDOW_FREQUENCY 30
#define WINDOW_RELATION (float(WINDOW_X)/float(WINDOW_Y))

#define MAP_X 256
#define MAP_Y 256
#define MAP_SCALE 1
#define MAP_DETAIL_CHANGES 4
#define MAP_NUM_OCTAVES 4

#define CELL_COUNT_GENES 4
#define CELL_CHANCE_MUTATION 0.2f
#define CELL_STARED_ENERGY 20
#define CELL_STARTED_NUM_GENE 0
